/*
 * File: app/controller/Company.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Example.controller.Company', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.ux.grid.Printer'
    ],

    models: [
        'Company'
    ],
    stores: [
        'Companies'
    ],
    views: [
        'CompanyGrid'
    ],

    onPrint: function(button, e, options) {
        var grid = button.up('companygrid');

        Ext.ux.grid.Printer.printAutomatically = false;
        Ext.ux.grid.Printer.print(grid);    
    },

    init: function(application) {
        this.control({
            "companygrid button#print": {
                click: this.onPrint
            }
        });
    }

});
